"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 1.8.18.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# from .email_info import EMAIL_USE_TLS, EMAIL_HOST, EMAIL_HOST_USER,EMAIL_HOST_PASSWORD,EMAIL_PORT
#
# EMAIL_USE_TLS = EMAIL_USE_TLS
# EMAIL_HOST = EMAIL_HOST
# EMAIL_HOST_USER = EMAIL_HOST_USER
# EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
# EMAIL_PORT = EMAIL_PORT


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j+$xcc#tr_u3#a_mjogz1v^w-y4j1od&7p9j#y@2s_zkwk0lmi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False



ALLOWED_HOSTS = ['califuse.com', 'www.califuse.com', 'http://www.califuse.com']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #third party apps
    'crispy_forms',
    'registration',
    'fontawesome',
    'profiles',
    #my apps
    'cali',
    'mainproj',
    'connect',
    'joins',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'mainproj.middleware.ReferMiddleware',
)

ROOT_URLCONF = 'mainproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'mainproj.wsgi.application'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mainproj_db',
        'USER': 'ryan',
        'PASSWORD': 'georgia23',
        'HOSTNAME': 'web507.webfaction.com',
        'PORT': 3306,
    }
}




# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#authorization... I think
AUTH_PROFILE_MODULE = "mainproj.UserProfile"
CRISPY_TEMPLATE_PACK = 'bootstrap3'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# STATIC_URL = '/static/'
STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_pro", "static_root")
STATIC_ROOT = '/home/califuse/webapps/cali_static_new/static'

# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static_in_pro", "our_static"),
#     '/home/califuse/webapps/cali_home/src/static_in_pro/our_static',
# ]

STATICFILES_DIRS = (
    '/home/califuse/webapps/cali_static_new/static',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/califuse/webapps/cali_static_new/media'

MEDIAFILES_DIRS = (
    '/home/califuse/webapps/cali_static_new/media/',
)

AUTH_PROFILE_MODULE = "mainproj.UserProfile"

CRISPY_TEMPLATE_PACK = 'bootstrap3'

#Django registration redux settings
ACCOUNT_ACTIVATION_DAYS = 365
REGISTRATION_AUTO_LOGIN = True
SITE_ID = 1
LOGIN_REDIRECT_URL = '/' #Change to '/Profile/' to redirect login to profile page
REGISTRATION_AUTO_LOGIN = True

# Email settings
EMAIL_HOST = 'smtp.webfaction.com'
EMAIL_HOST_USER = 'califuse'
EMAIL_HOST_PASSWORD = 'Califuse'
DEFAULT_FROM_EMAIL = 'co@califuse.com'
SERVER_EMAIL = 'co@califuse.com'
